SET(Bricks_VERSION 0.0.1)
SET(Bricks_MAJOR_VERSION 0)
SET(Bricks_MAJOR_MINOR_VERSION 000001)
SET(Bricks_VERSION_STRING "0.0.1 (Dev)")
SET(Bricks_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
